@startuml

class データ用申込ドメイン {
  プラン, 端末, メアド...
  申込()\n// 内部は非公開のまま、手元の情報で\n     端末有無の条件分岐や、データ用処理の呼び出しをごりごりやる
}
interface メールリポジトリ {
  端末あり(プラン, 端末, メアド...)
  端末なし(プラン, メアド...)
}
class "メール...？" as メール
データ用申込ドメイン -d-> メールリポジトリ
メールリポジトリ -[hidden]r-> メール

@enduml
