@startuml

class データ用申込ドメイン {
  プラン, 端末, メアド...
  申込()\n// 内部は非公開のまま、手元の情報で\n     <font color=red>メールをきっちり組み立てて送信()を呼ぶ</font>
}
interface メールリポジトリ {
  送信(メール)
}
class メール
データ用申込ドメイン -d-> メールリポジトリ
メールリポジトリ -r-> メール

' 名詞の流れが出来たけど、やっぱりテストにはモックが必要
' 申込()が void である限り変わらない

@enduml
