@startuml

class Main {
    プラン, 端末, 特典, 事業者コード...
}
package domain.提携事業者 {
  class A社用料金ドメイン
  class B社用料金ドメイン
}

package domain.料金 {
  class 料金計算ドメイン {
    料金 計算(プラン, 端末, 特典, <font color=red>事業者料金計算ドメイン</font>)
  }
  class 料金
  interface 事業者料金計算ドメイン
}

Main --> 事業者料金計算ドメイン : 1. 実クラスで new しておく
Main -d-> 料金計算ドメイン : 2. 実クラスも一緒に渡す
A社用料金ドメイン -u-|> 事業者料金計算ドメイン
B社用料金ドメイン -u-|> 事業者料金計算ドメイン
料金計算ドメイン -l-> 事業者料金計算ドメイン : 3. 中身は知らないけど頼る
料金計算ドメイン -r-> 料金 : 4. 算出

' C社が増えたときに料金側に影響する
' 料金側が全事業者を知らないといけない

' 必ずしも autowired や di が必要だったり、repository に限る話ではない

@enduml
