@startuml

class 申込内容 {
  配送予定日 or 何らかのエラー 申し込む(申込内容)
}
enum プラン {
  3GB
  6GB
  12GB
  20GB
}
class プランValue {
  String // pv001, pv002...
  {static} create(プラン)
}

申込内容 --> 名前
申込内容 --> プラン
申込内容 --> 年齢 : 実判定は委譲
申込内容 --> 住所
申込内容 --> 申込日

プランValue -u-> プラン : ビジネスとシステムの境界

class 年齢 {
  is未成年()
}

class 住所 {
  is本州()
}

class 配送予定日 {
  {static} create(住所, 申込日)
}

配送予定日 --> 住所
配送予定日 --> 申込日 : ルールや実装は\n配送日側が\n握っている
class 何らかのエラー

申込内容 -u->  "0 or 1" 何らかのエラー : return するかも
申込内容 -r->  "0 or 1" 配送予定日 : return するかも

' io があるとテストがしづらい
' こいつらどこから生まれたの？ -> リポジトリの登場

@enduml