@startuml

package domain {
  class "画面...??" as 画面

  enum プラン {
    3GB_data(pv001)
    6GB_data(pv002)
    3GB_voice(pv003)
    6GB_voice(pv004)
  }

  class 端末

  class 年齢 {
    + bool is未成年()
  }

  class メアド

  class 住所 {
    + bool is本州()
  }

  class "配送...??" as 配送
}

@enduml