@startuml

package domain {
  package mail {
    class メール {
      宛先, 件名, 本文
      + {static} create(プラン, メアド, 端末)
    }
  }
  package 申込 {
    class 申込内容 {
      プラン, 端末, 年齢, メアド, 住所, 申込日時
    }
  }
  申込内容 -d-> メール
  package plan {
    enum プラン
  }
  申込内容 --> プラン
  メール -r-> プラン
}

' 全部のプランや端末を知らないといけない
' 解約も実装したら create解約() とか出来る　実質双方向
' 自動テストも結合テストも辛い

@enduml

