@startuml

package domain {
class 申込ドメイン {
  メアド, 年齢, 住所, プラン, スマホ
  + void 申込()
}

interface メールリポジトリ {
  + void 送信_端末あり(メアド, プラン, スマホ)
  + void 送信_端末なし(メアド, プラン)
}

interface 配送リポジトリ {
  + void 配送(スマホ, 住所)
}

申込ドメイン --> メールリポジトリ
申込ドメイン -d-> 配送リポジトリ

メールリポジトリ -[hidden]r-> 配送リポジトリ
}

@enduml