@startuml

package domain {
class 申込ドメイン {
  メアド, 年齢, 住所, プラン, スマホ
  + void 申込()
}
note "年齢の is未成年() を使うのはここ" as ドメインNote
ドメインNote .d. 申込ドメイン
note "未成年の場合は何かが起きる" as ドメインNote2
ドメインNote2 .r. 申込ドメイン

interface メールリポジトリ {
  + void 送信_端末あり(メアド, プラン, スマホ)
  + void 送信_端末なし(メアド, プラン)
}

interface 配送リポジトリ {
  + void 配送(スマホ, 住所)
}
note "住所の is本州() を使うのはここ" as 配送Note
配送Note .u. 配送リポジトリ

申込ドメイン --> メールリポジトリ : 条件分岐
申込ドメイン -d-> 配送リポジトリ : メール送信より先\nただし端末がある場合のみ

メールリポジトリ -[hidden]r-> 配送リポジトリ
}

@enduml