@startuml

class 申込ドメイン {
  プラン, 端末, 年齢, メアド, 住所
  + void 申込()
}

interface メールリポジトリ {
  + void 送信_端末あり(プラン, 端末, メアド)
  + void 送信_端末なし(プラン, メアド)
}

申込ドメイン --> メールリポジトリ : 条件分岐

class "メール...??" as メール
メールリポジトリ -[hidden]r-> メール

@enduml