@startuml

package application {
class 申込サービス {
  + void 申込()
}
}

package domain {
class 申込ドメイン {
  プラン, 端末, 年齢, メアド, 住所
  + <font color=red>メール メール作成()</font>
}

interface メールリポジトリ {
  + void 送信(メール)
}

申込ドメイン -d-> メール : new メール(プラン, 端末, メアド)

class メール
}
メールリポジトリ -r-> メール
申込サービス -r-> 申込ドメイン : " メールくれ"
申込サービス -r-> メールリポジトリ : メールを渡す

@enduml