@startuml

package domain {
  enum エラー {
    未成年エラー（未成年の方はお申し込みできません。）
  }

  class 申込内容 {
    メアド, 年齢, 住所, プラン, スマホ, 申込日
    + 受付内容 or エラー 申込()
    - メール メール作成()
    - 配送申込 配送作成()
  }

  enum プラン {
    3GB（pv001）
    6GB（pv002）
    12GB（pv003）
    20GB（pv004）
  }

  class 年齢 {
    + bool is未成年()
  }

  class 住所 {
    + bool is本州()
  }

  申込内容 --> 年齢 : 年齢チェック

  class 配送予定日 {
    + {static} create(住所, 申込日)
    - {static} create本州(申込日)
    - {static} create本州以外(申込日)
  }

  配送予定日 --> 住所
  配送予定日 --> 申込日

  class 配送申込 {
    + {static} create(住所, スマホ, 申込日)
  }

  配送申込 --> 配送予定日
  配送申込 --> "1" スマホ

  class 受付内容 {
    + {static} create(メアド, 住所, プラン, スマホ, 申込日)
  }

  受付内容 --> "0..1" 配送申込
  受付内容 --> メール

  class メール {
    宛先, 件名, 本文
    + {static} create(メアド, プラン, スマホ)
  }

  メール --> プラン
  メール --> "0..1" スマホ
  メール --> メアド

  申込内容 -r-> 受付内容 : return するかも
  申込内容 -u-> エラー : return するかも
}

@enduml
