@startuml

class Main {
  申込()
}

class データ用申込ドメイン {
  プラン, 端末, メアド...
  メール メール作成()\n// 内部は非公開のまま、手元の情報で\n     <font color=red>メールをきっちり組み立てて return する</font>
}
interface メールリポジトリ {
  送信(メール)
}
class メール
メールリポジトリ -r-> メール
データ用申込ドメイン --> メール
Main -r-> データ用申込ドメイン
Main --> メールリポジトリ

' これならテストにモックがいらない
' メールリポジトリからもプランとかが消えた

@enduml
